/**
 * Catalogue of characters and clips available to the sprite sheet tool.
 *
 * GENERATED by prepare_models.py - rerun it after adding or removing GLBs.
 * Display names are preserved across runs, so renaming an entry here sticks.
 *
 * A file listed in both arrays is self-contained: it carries its own mesh and
 * its own animation, and retargets onto itself.
 */
const MODEL_DIR = 'models/';

const CHARACTERS = [
    { id: 'bikeridle',      name: 'Biker',           file: 'BikerIdle.glb' },
    { id: 'hatguyidle',     name: 'Hat Guy',         file: 'HatGuyIdle.glb' },
    { id: 'hipsteridle',    name: 'Hipster',         file: 'HipsterIdle.glb' },
    { id: 'blonde',         name: 'Blonde Block',    file: 'Meshy_AI_Blonde_Block_Figure_0205222923_texture.glb' },
    { id: 'boxer',          name: 'Boxing Champion', file: 'Meshy_AI_Boxing_Champion_Brick_0204044330_texture.glb' },
    { id: 'crazy',          name: 'Crazy',           file: 'Meshy_AI_crazy_0204044557_texture.glb' },
    { id: 'executive',      name: 'Executive',       file: 'Meshy_AI_Executive_0205100642_texture.glb' },
    { id: 'karate',         name: 'Karate Master',   file: 'Meshy_AI_Karate_Master_Toy_0204084344_texture.glb' },
    { id: 'rocker',         name: 'Roblox Rocker',   file: 'Meshy_AI_Roblox_Rocker_0203211925_texture.glb' },
    { id: 'sentinel',       name: 'Robot Sentinel',  file: 'Meshy_AI_Robot_Sentinel_0204044455_texture.glb' },
    { id: 'stylish',        name: 'Stylish Brick',   file: 'Meshy_AI_Stylish_Brick_Figure_0204044514_texture.glb' },
    { id: 'valley',         name: 'Valley Girl',     file: 'Meshy_AI_valley_girl_0204084358_texture.glb' },
    { id: 'wrestler',       name: 'Wrestler',        file: 'Meshy_AI_Wrestler_0204084351_texture.glb' },
    { id: 'punkidle',       name: 'Punk',            file: 'PunkIdle.glb' },
    { id: 'roadworkeridle', name: 'Road Worker',     file: 'RoadWorkerIdle.glb' },
];

const CLIPS = [
    { id: 'bikeridle',                                       name: 'Biker Idle',                                      file: 'BikerIdle.glb' },
    { id: 'bikerwalk',                                       name: 'Biker Walk',                                      file: 'BikerWalk.glb' },
    { id: 'hatguyidle',                                      name: 'Hat Guy Idle',                                    file: 'HatGuyIdle.glb' },
    { id: 'hatguywalk',                                      name: 'Hat Guy Walk',                                    file: 'HatGuyWalk.glb' },
    { id: 'hipsteridle',                                     name: 'Hipster Idle',                                    file: 'HipsterIdle.glb' },
    { id: 'hipsterwalk',                                     name: 'Hipster Walk',                                    file: 'HipsterWalk.glb' },
    { id: 'meshy_ai_blonde_block_figure_0205222923_texture', name: 'Meshy AI Blonde Block Figure 0205222923 Texture', file: 'Meshy_AI_Blonde_Block_Figure_0205222923_texture.glb' },
    { id: 'cheering2',                                       name: 'Cheering 2',                                      file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Cheering (1).glb' },
    { id: 'cheering',                                        name: 'Cheering',                                        file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Cheering.glb' },
    { id: 'defeat',                                          name: 'Defeat',                                          file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Defeat.glb' },
    { id: 'defeated',                                        name: 'Defeated',                                        file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Defeated.glb' },
    { id: 'excited',                                         name: 'Excited',                                         file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Excited.glb' },
    { id: 'happyidle',                                       name: 'Happy Idle',                                      file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Happy Idle.glb' },
    { id: 'idle2',                                           name: 'Idle (boxing)',                                   file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Idle (1).glb' },
    { id: 'idle',                                            name: 'Idle',                                            file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Idle.glb' },
    { id: 'kicking',                                         name: 'Kicking',                                         file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Kicking.glb' },
    { id: 'knockeddown',                                     name: 'Knocked Down',                                    file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Knocked Down.glb' },
    { id: 'knockedout2',                                     name: 'Knocked Out 2',                                   file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Knocked Out (1).glb' },
    { id: 'knockedout',                                      name: 'Knocked Out',                                     file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Knocked Out.glb' },
    { id: 'mmakick2',                                        name: 'MMA Kick 2',                                      file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Mma Kick (1).glb' },
    { id: 'mmakick',                                         name: 'MMA Kick',                                        file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Mma Kick.glb' },
    { id: 'punching2',                                       name: 'Punching 2',                                      file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Punching (1).glb' },
    { id: 'punching',                                        name: 'Punching',                                        file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Punching.glb' },
    { id: 'sadidle',                                         name: 'Sad Idle',                                        file: 'Meshy_AI_Roblox_Rocker_0203211925_texture@Sad Idle.glb' },
    { id: 'punkidle',                                        name: 'Punk Idle',                                       file: 'PunkIdle.glb' },
    { id: 'punkwalk',                                        name: 'Punk Walk',                                       file: 'PunkWalk.glb' },
    { id: 'roadworkeridle',                                  name: 'Road Worker Idle',                                file: 'RoadWorkerIdle.glb' },
    { id: 'roadworkerwalk',                                  name: 'Road Worker Walk',                                file: 'RoadWorkerWalk.glb' },
];
